### ISSUE TITLE
Crash on function example with -run

### ISSUE THREAD

**Issue by kmantel** [ModECI/MDF#141]
The `-run` argument is not currently tested in examples, and when adding it the following example fails. 

`python run_test_function_json.py -run`:
```
Loaded a graph from test_function.json, Root(s): dict_keys(['Stateful_Parameters'])

Init graph: stateful_parameters_example

  Init node: counter_node
    Checking whether function: evaluated_counter_node_count_next_value with args {'increment': 'increment', 'count': 'count'} is sufficiently determined by known vars ['constant', 'increment', 'count']
    Are all of ['increment', 'count'] in ['constant', 'increment', 'count']? [True, True]
all_params_to_check: [Parameter (increment), value = 1, Parameter (count), default_initial_value = 0, value = evaluated_counter_node_count_next_value]
    Checking whether parameter: increment with args: None, value: 1 (<class 'int'>) is sufficiently determined by known vars ['constant', 'increment', 'count', 'evaluated_counter_node_count_next_value']
    Are all of [] in ['constant', 'increment', 'count', 'evaluated_counter_node_count_next_value', 'increment']? [], i.e. True
    Checking whether parameter: count with args: None, value: evaluated_counter_node_count_next_value (<class 'str'>) is sufficiently determined by known vars ['constant', 'increment', 'count', 'evaluated_counter_node_count_next_value', 'increment']
    Are all of ['evaluated_counter_node_count_next_value'] in ['constant', 'increment', 'count', 'evaluated_counter_node_count_next_value', 'increment', 'count']? [True], i.e. True
======   Evaluating at t = 0  ======

Evaluating graph: stateful_parameters_example, root nodes: ['counter_node'], with array format numpy
 node-based conditions
  
 termination conditions
  TimeScale.ENVIRONMENT_SEQUENCE: Never()
  TimeScale.ENVIRONMENT_STATE_UPDATE: AllHaveRun()
> Evaluating time step: Time(environment_sequence: 0, environment_state_update: 0, consideration_set_execution: 0)

  ---------------
  Evaluating Node: counter_node with ['increment', 'count']
    Initial eval of <Parameter (increment), value = 1> = 1 
    Evaluating Function (evaluated_counter_node_count_next_value), function = count + increment, args = {'increment': 'increment', 'count': 'count'} with [increment=1, count=0.0], i.e. [None]
      Arg: increment became: 1
      Arg: count became: 0
Traceback (most recent call last):
  File "run_test_function_json.py", line 64, in <module>
    main()
  File "run_test_function_json.py", line 47, in main
    eg.evaluate()
  File "MDF/src/modeci_mdf/execution_engine.py", line 790, in evaluate
    time_increment=time_increment, array_format=array_format
  File "MDF/src/modeci_mdf/execution_engine.py", line 642, in evaluate
    curr_params, array_format=array_format
  File "MDF/src/modeci_mdf/execution_engine.py", line 142, in evaluate
    if "onnx_ops." in expr:
TypeError: argument of type 'NoneType' is not iterable
```

I think this is related to the MDF_S/_0 translator, because changing the following line in the input file allows execution to succeed:
https://github.com/ModECI/MDF/blob/a67e0b5283b203de4ab33d8690e7967c5dd7b058/examples/MDF/test_function.json#L26

```diff
-                                 "function": "count + increment",
+                                 "value": "count + increment", 
```

This is because MDF expects a standard function in the key "function" rather than a string expression.

**Comment by Shanka123** [comment]
@kmantel This is an old json file which was used to test if an expression is supported under "function" key. It can be deleted.  The current MDF_0 format has only value as key for dicts inside functions. (https://github.com/ModECI/MDF/blob/translator_v2/examples/MDF/translation/Translated_States.json)
This is in translator_v2 branch and hasn't been merged yet with development.

**Comment by kmantel** [comment]
Ok, so should the entire test file (run_test_function_json.py) be deleted, or should the test_function.json be replaced with another file here?

**Comment by Shanka123** [comment]
Yes, both run_test_function_json.py and test_function.json can be deleted.
